# Generated by Django 4.2.3 on 2023-07-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_api', '0002_rename_disease_presentdisease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmSymptom',
        ),
        migrations.DeleteModel(
            name='QNA',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
