# Generated by Django 4.2.3 on 2023-07-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('RecipeId', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('RecipeIngredientParts', models.CharField(max_length=10000)),
                ('RecipeInstructions', models.CharField(max_length=10000)),
                ('Calories', models.FloatField()),
                ('FatContent', models.FloatField()),
                ('SaturatedFatContent', models.FloatField()),
                ('CholesterolContent', models.FloatField()),
                ('SodiumContent', models.FloatField()),
                ('CarbohydrateContent', models.FloatField()),
                ('FiberContent', models.FloatField()),
                ('SugarContent', models.FloatField()),
                ('ProteinContent', models.FloatField()),
                ('CookTime', models.IntegerField()),
                ('PrepTime', models.IntegerField()),
                ('TotalTime', models.IntegerField()),
                ('image_link', models.CharField(max_length=10000)),
            ],
        ),
    ]
