# Generated by Django 4.2.3 on 2023-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_api', '0002_alter_recipe_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(default='Breakfast', max_length=100),
        ),
    ]
